import './globals.css'
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import NextAuthProvider from "@/providers/NextAuthProvider"
//import { Inter } from 'next/font/google'

//
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="ok">
         <ToastContainer />
         <NextAuthProvider>
             {children}
          </NextAuthProvider>
      </body>
    </html>
  )
}
